### ISSUE TITLE
Как использовать числительную переменную в данных?

### ISSUE THREAD

**Issue by kevinblo** [AlexxIT/YandexDialogs#2]
Пытюсь открыть жалюзи на х%. Как правильно "х" передать? Проговаривает правильно.

```
 cover_balcony:
   async_action: true
   speech:
     text: >-
       Открываю на {{ x }} процентов
   action:
     - service: cover.set_cover_position
       data:
         entity_id: cover.balcony_roll_cover_2
         position: x
```
